site_name: Metahyper Documentation
docs_dir: docs
repo_url: https://github.com/automl/metahyper
repo_name: automl/metahyper
edit_uri: ""
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

nav:
  - Introduction and Installation: 'README.md'
  - Getting started: 'getting_started.md'
  - The Api: 'api.md'
  - The Sampler: 'sampler.md'
  - The evaluation_fn function: 'evaluation_fn.md'
  - Parallelization: 'parallelization.md'
  - Contributing: 'CONTRIBUTING.md'
